### ISSUE TITLE
Page redirects everytime to the Discord Login Page 

### ISSUE THREAD

**Issue by Sawaya-ui** [Xwilarg/Discord-OAuth2-PHP#5]
Hey I had to redo the whole thing today because some things didn't work anymore and now I notice that I'm constantly redirected to the Discord login page. I have also entered the code 1 to 1 of the example and still the error.

**Comment by Xwilarg** [comment]
Thanks for the bug report,

Could you please give an example of what you did?

**Comment by Sawaya-ui** [comment]
Nevermind It's only Working on an Top Level Domain or so and not on an local Server
